# Files
executable = scriptcondor_performances_nano.sh
output = /afs/cern.ch/work/p/pmeiring/private/CMS/l1tdpg/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(Process).out
error = /afs/cern.ch/work/p/pmeiring/private/CMS/l1tdpg/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(Process).err
log = /afs/cern.ch/work/p/pmeiring/private/CMS/l1tdpg/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/log/scriptcondor_$(Process).log

#transfer_input_files = $(filename)
arguments            = $(filename)  /afs/cern.ch/work/p/pmeiring/private/CMS/l1tdpg/MacrosNtuples/l1macros/condorsubmission/OUTPUTDIR/output_$(Process).root CHANNEL GOLDENJSON

# File transfer behavior
#should_transfer_files = no
when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
request_memory = 100MB
request_disk   = 100MB

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 4000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue
+MaxRuntime = 1800

# Run job
queue filename matching files FILENAMES
